### ISSUE TITLE
Homework done!

### ISSUE THREAD

**Issue by neverbendeasy** [neverbendeasy/My-Simple-Tweets#1]
Please review @codepathreview @codepath

**Comment by codepathreview** [comment]
Nice to see you completed the required stories but you will be able to learn a lot more if you attempt the additional optional ones as well. A few notes after checking out the code:

* Consider adding better input validation and user feedback if values are invalid or empty
* Consider [better organizing your source files](http://guides.codepath.com/android/Organizing-your-Source-Files)
* Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#progress-within-actionbar) to your app whenever a network request goes out
* Consider including a check to see if internet is available to detect any network failures. Show an approrpiate message in case of failure.
* Good to see you were able to format the time-stamp cleanly (Consider externalizing the logic to `Utils`)
* Consider adding pull to refresh for the home timeline using the [SwipeRefreshLayout](http://guides.codepath.com/android/Implementing-Pull-to-Refresh-Guide)
* Good to see you added the tweet to the home timeline after you posted a new tweet
* Consider adding the character count for Compose Activity to limit to 140. See [this event handler](http://guides.codepath.com/android/Basic-Event-Listeners#textchangedlistener) for more details.
* Consider adding local persistence of tweets by using ActiveAndroid in the `Tweet` and `User`. See the [persistence guide](http://guides.codepath.com/android/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](http://guides.codepath.com/android/ActiveAndroid-Guide) for more details.

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.

**Comment by neverbendeasy** [comment]
Homework #4 done, please review @codepathreview @codepath

**Comment by codepathreview** [comment]
Decent submission. A few notes after checking out the code:

* In the future, definitely consider [additional polish for the UI](http://guides.codepath.com/android/Polishing-a-UI-Tips-and-Tools) by reviewing the [cloning a screen](http://guides.codepath.com/android/Cloning-a-Login-Screen-Layout-Guide) tutorial and Q&A and the [drawables](http://guides.codepath.com/android/Drawables) guide.
* For the sliding tabs, try [styling the tabs](https://guides.codepath.com/android/Sliding-Tabs-with-PagerSlidingTabStrip#customize-tab-styles) to customize their appearance.
* Remember to add an [indeterminate progress indicator](http://guides.codepath.com/android/Handling-ProgressBars#progress-within-actionbar) during background tasks
* Correctly and appropriately used OnClickListeners on the user's profile image to navigate to their profile view
* Good to see you properly communicated the user to the user timeline fragment from the profile activity.
* Glad to see you properly hooked up each of the different timelines to infinitely paginate.
* Nicely done architecting the fragments (base class and extension classes) such that you put as much code and logic as possible in the base class and then used abstract methods to define only the specific behavior where they differ!
* Consider adding local persistence of tweets by using ActiveAndroid in the `Tweet` and `User`. See the [persistence guide](http://guides.codepath.com/android/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](http://guides.codepath.com/android/ActiveAndroid-Guide) for more details.

Here's a detailed [Project 4 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_4_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you might be able to improve your submission. 

This week (Week 5), we are going to cover the last major piece to the Android puzzle and that is using the hardware and SDK components such as the camera, photo gallery, location, maps, etc. After that, Week 6 and week 7 we will be covering a few important intermediate topics such as more about styling and animation as well as testing.

Following the bootcamp, we are going to have a public demo day to celebrate the progress you've all made with our next batch of Android students and multiple companies attending to see the group projects that you all have built. We are going to help however we can over the next few weeks to get the team project apps in shape for that.
